package handlers_gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/WildEgor/fiber-gql/internal/models"
	gql "github.com/WildEgor/fiber-gql/internal/server"
)

// FindCapsuleByID is the resolver for the findCapsuleByID field.
func (r *entityResolver) FindCapsuleByID(ctx context.Context, id string) (*models.Capsule, error) {
	panic(fmt.Errorf("not implemented: FindCapsuleByID - findCapsuleByID"))
}

// Entity returns gql.EntityResolver implementation.
func (r *Resolver) Entity() gql.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
