// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/WildEgor/fiber-gql/internal/config"
	"github.com/WildEgor/fiber-gql/internal/handlers"
	"github.com/WildEgor/fiber-gql/internal/router"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*fiber.App, error) {
	appConfig := config.NewAppConfig()
	healthCheckHandler := handlers.NewHealthCheckHandler(appConfig)
	routerRouter := router.NewRouter(healthCheckHandler)
	app := NewApp(appConfig, routerRouter)
	return app, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
